// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFileNode } from "./ConfigFileNode";

export type AgentWorkspaceResponse = {
	agent_id: string;
	/**
	 * Display path with ~ prefix (e.g. "~/.claude")
	 */
	root_path: string;
	files: Array<ConfigFileNode>;
};
