// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFileType } from "./ConfigFileType";

export type ConfigFileNode = {
	/**
	 * Relative path from agent root (e.g. "settings.json", "skills/my-skill")
	 */
	path: string;
	name: string;
	type: ConfigFileType;
	/**
	 * Optional navigation target for directories (e.g. skills/ -> "/skills")
	 */
	link_to: string | null;
	/**
	 * Child nodes (only populated for directories)
	 */
	children: Array<ConfigFileNode>;
};
