// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigFileType } from "./ConfigFileType";

export type FileContentResponse = {
	path: string;
	name: string;
	file_type: ConfigFileType;
	content: string;
};
